[package]
name = "macros"
version = "0.0.0"
edition = "2021"
rust-version = "1.74"

[lib]
proc-macro = true

[dependencies]
macros-impl = { workspace = true }

proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
