version: "3"

services:
  redis:
    image: docker.io/redis:7-alpine
    ports:
      - "26379:6379"
  db:
    image: docker.io/groonga/pgroonga:3.1.8-alpine-12
    env_file:
      - ../config.env
    ports:
      - "25432:5432"
    volumes:
      - "./install.sql:/docker-entrypoint-initdb.d/install.sql:ro"
